### ISSUE TITLE
CodeReady Workspaces pod crashing in Integreatly 1.5

### ISSUE THREAD

**Issue by honghuac** [integr8ly/installation#1014]
## Description
Dead links to the consoles of CodeReady Workspaces and Launcher, found on the "Managing and protecting APIs using API management" walkthrough

Issue repeated in this project:
https://github.com/integr8ly/walkthrough-applications/issues/2

## Expected Behavior
Links should be working.

## Actual Behavior
Either links are dead, or consoles are not available.

## Environment
Integreatly 1.5-alpha, using Firefox to access the UI

**Comment by honghuac** [comment]
CodeReady project pod status:

`NAME                                  READY     STATUS             RESTARTS   AGE`
`codeready-5fcf68b6c5-tndhv            0/1       CrashLoopBackOff   112        9d`
`codeready-operator-7547984678-r649j   1/1       Running            3          9d`
`postgres-9d75bbfbc-7m4vp              1/1       Running            3          9d`

**Comment by honghuac** [comment]
Launcher project pod status:

`NAME                               READY     STATUS             RESTARTS   AGE`
`configmapcontroller-1-v2pgk        1/1       Running            2          9d`
`launcher-backend-5-tw2kn           1/1       Running            0          7h`
`launcher-creator-backend-2-brpnj   1/1       Running            2          9d`
`launcher-frontend-3-zn65h          1/1       Running            2          9d`
`launcher-sso-1-qfbrn               0/1       CrashLoopBackOff   119        9d`
`launcher-sso-postgresql-1-2bb4d    1/1       Running            2          9d`

**Comment by honghuac** [comment]
Problem for launcher resolved in Integreatly 1.5
But issue exists for codeready workspaces pod in Integreatly 1.5

**Comment by honghuac** [comment]
Resolution provided. https://github.com/RedHatWorkshops/dayinthelife-integration/blob/master/docs/Troubleshooting.md

**Comment by pawelpaszki** [comment]
Possible workaround exists and has been documented in the **Integreatly Workshop on RHPDS**
