### ISSUE TITLE
Fuse ServiceInstance not being removed when namespace deleted

### ISSUE THREAD

**Issue by aidenkeating** [integr8ly/installation#129]
When deleting a namespace which has a fuse ServiceInstance in it, the ServiceInstance is not being removed.

This can be reproduced by logging into the Integreatly webapp, waiting for the provisioning to complete and then removing the created namespaces. The users projects namespace will stay around due to a Fuse ServiceInstance with a finalizer on it.

@pmccarthy @maleck13

**Comment by pmccarthy** [comment]
Current (horrible) workaround:

```
kubectl proxy
NS=<namespace>
oc project $NS
echo "Removing Finalizers on Namespace: $NS"
oc delete --all all,secret,pvc > /dev/null
oc get ns $NS -o json > /tmp/$NS_tempfile.json
sed -ni '/kubernetes/!p' /tmp/$NS_tempfile.json
curl --silent -H "Content-Type: application/json" -X PUT --data-binary @/tmp/$NS_tempfile.json http://127.0.0.1:8001/api/v1/namespaces/$NS/finalize
```

**Comment by JameelB** [comment]
Closing as this has been resolved by  https://github.com/integr8ly/managed-service-broker/pull/13
