### ISSUE TITLE
No SSO on Red Hat applications associated to integreatly

### ISSUE THREAD

**Issue by davidffrench** [integr8ly/installation#130]
## Expected Behavior
Automatic login to all Applications from the integreatly dashboard.

## Actual Behavior
No SSO seems to be in place for Applications.

![2018-11-08_12-05-02](https://user-images.githubusercontent.com/1596014/48197779-aa5d5e00-e34e-11e8-93ec-40581c9a0f52.gif)

## Steps to Reproduce the Problem
  1. Click on any application from the integreatly dashboard.
  1. The applications login page is shown. No SSO in place.

## Specifications
  - Browser: Chrome

**Comment by camilamacedo86** [comment]
@davidffrench what was the branch/tag used to install the product?

**Comment by davidffrench** [comment]
@camilamacedo86 it was release-1.0.1

**Comment by maleck13** [comment]
@davidffrench we have single identity not full single sign on. There is a card to look at this but it is a much bigger change.
