### ISSUE TITLE
webapp operator uses latest tag of integreatly / tutorial-web-app

### ISSUE THREAD

**Issue by tremes** [integr8ly/installation#144]
## Description
webapp operator uses latest tag of integreatly / tutorial-web-app - https://github.com/integr8ly/installation/blob/master/evals/roles/webapp/defaults/main.yml#L10

## Expected Behavior
I think it should use master tag instead since the latest hasn't been modified for a month. 

## Actual Behavior
This brings old walkthroughs stuff to the environment installed from master.

## Steps to Reproduce
Just install from master and open W1A

**Comment by tremes** [comment]
@odra please take a look.

**Comment by odra** [comment]
Makes sense - it should be using the tag "1.0.0"

**Comment by trepel** [comment]
@odra I think the 'master' branch must not use tagged bits at all. Thus this is also incorrect:
https://github.com/integr8ly/installation/blob/master/evals/roles/webapp/defaults/main.yml#L7

The 'master' branch should point to latest&greatest bits of the other components. Only tagged (release version) bits should point to appropriate tagged bits.

**Comment by odra** [comment]
Yeah agreed - sorry about the confusion.

The "master" tag is the one that gets updated on every PR according to this script: https://github.com/integr8ly/tutorial-web-app/blob/master/scripts/docker_push.sh#L5

So master branch should use "master" tag.

**Comment by camilamacedo86** [comment]
Hi @tremes at another point it was discussed and the answer was that the components should use the master tag. See [here](https://github.com/integr8ly/installation/issues/226#issuecomment-444075037). So, in this way I understand that this issue could be closed do you agree? If not, I think that it need be raised to others in order to get a final position. Wdyt?

**Comment by tremes** [comment]
@camilamacedo86 well OK so master tag. Anyway I am still seeing 1.0.0 at https://github.com/integr8ly/installation/blob/master/evals/roles/webapp/defaults/main.yml#L8 so I am not sure whether this can be considered as done (I'd say that can't but need to try out)

**Comment by camilamacedo86** [comment]
The PR to fi it is: https://github.com/integr8ly/installation/pull/236

**Comment by tremes** [comment]
Yep I am in process of testing and hopefully will merge

**Comment by camilamacedo86** [comment]
Hi, @tremes since the PR which should fix it is merged. Please, feel free to re-opened if this issue is not solved at all.
