### ISSUE TITLE
Failed to login using Openshift identity provided in Enmasse

### ISSUE THREAD

**Issue by JameelB** [integr8ly/installation#149]
## Description
Failed to login to the Enmasse console when using the OpenShift identity provider. 

## Expected Behavior
Users should be able to successfully login to the Enmasse console via OpenShift identity provider.

## Actual Behavior
When logging in via the OpenShift identity provider, the following error shows:
```
Unexpected error when authenticating with identity provider
```

Upon authentication request via the identity provider, a status code of `502` is received.

## Steps to Reproduce
1. Run the installer
2. Open the webapp
3. Click on the Enmasse service in the services list
4. Click the `OpenShift` button in the Enmasse login page.
5. The following error should be seen:
![image](https://user-images.githubusercontent.com/9078522/48561121-3808f280-e8e7-11e8-9b21-1ad8fdb3e4fc.png)

**Comment by JameelB** [comment]
@philbrookes @pmccarthy @aidenkeating

**Comment by philbrookes** [comment]
It's worth pointing out that this is a bug prior to the merge of: https://github.com/integr8ly/installation/pull/123/files
And appears to still be malfunctioning afterwards, and so I suspect this is unrelated to that PR (even though it does feel like it is related)

It appears that enmasse runs it's own instance of keycloak.

**Comment by tremes** [comment]
I don't think this is related to the Phil's commit. I've encountered this issue as well and I think this happens when the Pods (likely keycloak instance Phil mentioned) in the related Enmasse namespace are not ready yet (and you try to login).

**Comment by maleck13** [comment]
If it is related to all the pods not being ready, is this something we want to fix in the installer (IE ensure we wait until all the pods or CR are set to ready?

**Comment by tremes** [comment]
Yes I think it would help, but it can be another issue as well. I'll try to check once the QE cluster is back.

**Comment by JameelB** [comment]
@maleck13 @tremes I've checked Enmasse's SSO and the following [error](https://gist.github.com/JameelB/c4180bb5e3fc1c6e246f711b0522d7a7) is logged when I try to login to the Enmasse console.

**Comment by maleck13** [comment]
Ok so this is actually to do with the the self signed cert not being trusted. @david-martin this is something we have known about for a while, is there a work around or does it just require an upgrade of EnMasse?

**Comment by david-martin** [comment]
> require an upgrade of EnMasse

@maleck13 this is my understanding, yes.
Switching to valid certs with LetsEncrypt recently seems to have broke the temporary fix we had from Ulf for self signed certs. 
Latest version of enmase has this fix https://github.com/EnMasseProject/enmasse/issues/1631
