### ISSUE TITLE
Error "jsonpointer module is not available" is faced when try to install with master branch

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/installation#156]
## Description
Unable to install the product with master branch. 

```
TASK [rhsso : [user generation: evals01@example.com] add user to realm template /tmp/keycloak-realm.json] *************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "jsonpointer module is not available"}
```

## Expected Behavior
Finish the installation with success.

## Actual Behavior
Following the error faced.

```
TASK [rhsso : [user generation: evals01@example.com] add user to realm template /tmp/keycloak-realm.json] *************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "jsonpointer module is not available"}
```

## Environment

* Operating system: MacOS - 10.14
* OpenShift version:v3.10.14

```shell
$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server https://master.camila-7da4.openshiftworkshop.com:443
openshift v3.10.14
kubernetes v1.10.0+b81c8f8
```

```shell
 $ ansible --version
ansible 2.7.1
  config file = /Users/camilamacedo/integr8ly/installation/evals/ansible.cfg
  configured module search path = [u'/Users/camilamacedo/integr8ly/installation/evals/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```
AND

```
 $ ansible --version
ansible 2.6.0
  config file = /Users/camilamacedo/integr8ly/installation/evals/ansible.cfg
  configured module search path = [u'/Users/camilamacedo/integr8ly/installation/evals/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

* Project Version/Tag:master branch (Date 19/November/2018)

## Steps to reproduce
- Create an OCP env with the version `v3.10.14` (Following steps on: Integr8ly Installation on RHPDS Customer Success)
- Setup the host file and execute the installer

## Observations:
It shows be caused by the following change https://github.com/integr8ly/installation/commit/77d41a3b29392b5835323f7d41e0b3deecb9769c#diff-ab0d7b093f6833b390f68d040b7c4bf0R20 and an specific issue with MacOsX and python. See [here](https://github.com/ansible/ansible/issues/15019#issuecomment-234218072) 

Shows that add the following workrround in the inventory solve the issue. 

```
[localhost]
localhost ansible_connection=local ansible_python_interpreter=python

```

**Comment by camilamacedo86** [comment]
@philbrookes I am trying to install the master branch and I am facing this issue. It shows caused by the PR: https://github.com/integr8ly/installation/commit/77d41a3b29392b5835323f7d41e0b3deecb9769c#diff-ab0d7b093f6833b390f68d040b7c4bf0R20https://github.com/integr8ly/installation/commit/77d41a3b29392b5835323f7d41e0b3deecb9769c#diff-ab0d7b093f6833b390f68d040b7c4bf0R20. Please, could you give me a hand here?

**Comment by camilamacedo86** [comment]
PR made to fix it is: https://github.com/integr8ly/installation/pull/159

**Comment by odra** [comment]
Thanks for linking the pr :+1:

**Comment by camilamacedo86** [comment]
@odra should it not keep the issue opening until the PR be merged?

**Comment by odra** [comment]
lol sorry closed the wrong issue ;)

**Comment by camilamacedo86** [comment]
Solved
