### ISSUE TITLE
Install script - [WARNING] - TASK [include_role : che] 

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/installation#168]
## Description
The following is shown when is trying to install.  

## Expected Behavior
Do not check warnings. 

## Actual Behavior
Following the WARNING.
```shell

TASK [include_role : che] ************************************************************************************************************
 [WARNING]: While constructing a mapping from /Users/camilamacedo/integr8ly/installation/evals/roles/che/tasks/main.yml, line 66,
column 3, found a duplicate dict key (include_tasks). Using last defined value only.

```

## Environment

* Operating system: MacOS 10.14 
* OpenShift version:
```shell
$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server https://master.camila-8c31.openshiftworkshop.com:443
openshift v3.10.14
kubernetes v1.10.0+b81c8f8
```

* Ansible version:
```shell
$ ansible --version
ansible 2.6.0
  config file = /Users/camilamacedo/integr8ly/installation/evals/ansible.cfg
  configured module search path = [u'/Users/camilamacedo/integr8ly/installation/evals/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```
* Project Version/Tag: maser

## Steps to reproduce
**IMPORTANT:**:
- From a Mac with the above environment setup try to install it.

**Comment by odra** [comment]
We just need to move one of the "include_task" directive to its own task.

**Comment by camilamacedo86** [comment]
The PR to solve it is: https://github.com/integr8ly/installation/pull/186

**Comment by camilamacedo86** [comment]
Done.

**Comment by camilamacedo86** [comment]
**Closing it as outdated**. 

Shows that the master was changed since the warning so long is faced. The error faced after the merge is because the task was removed. See [here](https://github.com/integr8ly/installation/search?q=deploy-persistent-volume.yml&type=Code).
