### ISSUE TITLE
Unable to install because the task "TASK [gitea : Wait for Gitea pods to be ready]" is falling

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/installation#173]
## Description
Unable to install because the task "TASK [gitea : Wait for Gitea pods to be ready]" is falling

## Expected Behavior
No face errors.

## Actual Behavior
```shell
fatal: [127.0.0.1]: FAILED! => {"attempts": 30, "changed": true, "cmd": "oc get pods --namespace=gitea --selector='deployment=gitea' -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}' | wc -w", "delta": "0:00:00.367634", "end": "2018-11-20 23:08:44.468932", "rc": 0, "start": "2018-11-20 23:08:44.101298", "stderr": "", "stderr_lines": [], "stdout": "       0", "stdout_lines": ["       0"]}

PLAY RECAP ***************************************************************************************************************************************************
127.0.0.1                  : ok=647  changed=339  unreachable=0    failed=1   
master.calondon-aa64.openshiftworkshop.com : ok=2    changed=1    unreachable=0    failed=0 
```
## Environment

* Operating system: MacOS 10.14
* OpenShift version:
```shell
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server https://master.calondon-aa64.openshiftworkshop.com:443
openshift v3.10.14
kubernetes v1.10.0+b81c8f8
```

* Ansible version:
```shel
ansible 2.7.2
  config file = /Users/camilamacedo/integr8ly/installation/evals/ansible.cfg
  configured module search path = [u'/Users/camilamacedo/integr8ly/installation/evals/library']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Oct  2 2018, 11:42:04) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]

```
* Project Version/Tag: master

## Steps to reproduce
Try to install using the master branch.
IMPORTANT: Required the following fixes in order to be able to go further this task.
- https://github.com/integr8ly/installation/pull/159
- https://github.com/integr8ly/installation/pull/169
- https://github.com/integr8ly/installation/pull/172

**Comment by camilamacedo86** [comment]
@pb82, please could you check? It shows started to occur after the PR: https://github.com/integr8ly/installation/commit/3e9149760e1abf261e82291b1e1d6e0d794a9343#diff-28e258baeacaad79b4e1c1ddb9184701

**Comment by pb82** [comment]
@camilamacedo86 looks like it exhausted the retries. Can you try again and observe the gitea workspace? Does it start deploying postgres and gitea? It's possible that pulling the gitea image took too long.

**Comment by camilamacedo86** [comment]
@pb82 it shows solved with the latest changes in the master. I am closing this one.
