### ISSUE TITLE
Remove the hosts file from Git and replace with a template file which should be used to create the hosts file

### ISSUE THREAD

**Issue by craicoverflow** [integr8ly/installation#175]
## Description

At present when we clone this repository the `hosts` file in `evals/inventories` needs to be modified to suit the local environment.

* Whenever switching branch we need to `git stash` then `git stash apply` again.
* When adding changes we need to be extra careful not to add the custom `hosts` file and push it to GitHub.

## Solution

1. Remove the `hosts` file from Git.
2. Add `evals/inventories/hosts` to `.gitignore`.
3. Create a copy and call it `hosts.default` or `hosts.template` which will be in Git. This will have the default values.
4. Add a step to the README where you should copy the template file to a new `hosts` file:
```bash
$ cp evals/inventories/hosts.default evals/inventories/hosts
```
5. Make changes to `evals/inventories/hosts` to suit your own setup.

Implementing this method would ensure a custom `hosts` file would never end up on GitHub and there would be no extra steps to do something simple like switching to a new branch.

Thoughts?

**Comment by odra** [comment]
Which changes do you need? Is it just the master host that needs to be changed?

**Comment by craicoverflow** [comment]
> Which changes do you need? Is it just the master host that needs to be changed?
> 
> We could create a simple playbook to generate the inventory file if needed.

At present it is just the `master` host that needs to be changed yes.

**Comment by odra** [comment]
I like your suggestion (still think we can roll with it) but was wondering if we could automate this task later.

**Comment by camilamacedo86** [comment]
Create the PR: https://github.com/integr8ly/installation/pull/184

**Comment by camilamacedo86** [comment]
Done.
