### ISSUE TITLE
Uninstall playbook corrupting master-config file when SSO identity provider doesn't exist

### ISSUE THREAD

**Issue by pmccarthy** [integr8ly/installation#179]
## Description
Following a failed install where the RHSSO identity provider does not get added to the master-config file on the Openshift master nodes, should the uninstall playbook get executed, it will corrupt the master-config file as it tries to remove the identity provider even though it isn't present in the master-config file.

The end result is that the config file gets corrupted so when the master services are restarted by the uninstall playbook, the master nodes go into an error state.

## Expected Behavior
The uninstall playbook should check to see if the RHSSO identity provider exists in the master-config file before trying to remove it. If the provider does not exist, it should skip the config update and not restart master services.

## Steps to reproduce

- Comment out the install playbook code block [1] that adds the SSO identity provider
- Run the install playbook
- Run the uninstall playbook - this should result in the master-config file getting corrupted and break the master nodes upon restart.

[1] https://github.com/integr8ly/installation/blob/master/evals/playbooks/install.yml#L225-L237

**Comment by pmccarthy** [comment]
@tremes FYI

**Comment by tremes** [comment]
Thanks @pmccarthy. As I said I think this has the highest priority - at least from QE point of view (we simply can't destroy the cluster with each unsuccessful install/uninstall :-))

**Comment by trepel** [comment]
A bit related PR (not fixing this)
https://github.com/integr8ly/installation/pull/187

It might be good to review/incorporate that change while doing this.

**Comment by tremes** [comment]
I would suggest to create some general issue like "Make uninstall script idempotent". WDYT guys? Because now I am facing issue "The error was: 'enmasse_namespace' is undefined".

**Comment by tremes** [comment]
I didn't verify it  but this might be already fixed by https://github.com/integr8ly/installation/commit/ef2c791450a2e83c1ab025d4c59465c962ba9393

**Comment by trepel** [comment]
This has been fixed by https://github.com/integr8ly/installation/pull/190
