### ISSUE TITLE
Can't login to OpenShift console after install on 3.11

### ISSUE THREAD

**Issue by tremes** [integr8ly/installation#194]
## Description
Can't login to OpenShift console (using admin@example.com or evals01@example.com users) after fresh install on PDS on OS 3.11. 

## Expected Behavior
Successful login
## Actual Behavior
It just says "An authentication error occurred." and there's following warning in sso pod in sso namespace:
 ```
15:56:17,647 WARN  [org.keycloak.events] (default task-248) type=CODE_TO_TOKEN_ERROR, realmId=openshift, clientId=openshift-client, userId=null, ipAddress=10.1.8.1, error=invalid_client_credentials, grant_type=authorization_code

```

**Comment by david-martin** [comment]
In the openshift master logs I was seeing this:

```
E1122 16:56:20.599127       1 errorpage.go:26] AuthenticationError: Invalid client secret
```

Looks like the clientSecret in the master-config.yml didn't match the client secret in SSO.

I updated the clientSecret in my master-config.yml to match what was in SSO, restarted the master & now login is working

**Comment by camilamacedo86** [comment]
@david-martin @tremes I have been using this change in last 2 days and did not face issues. Yesterday, after pulling the master I started to face the same error described here. I will do more tests as soon as possible and I let you know.

**Comment by tremes** [comment]
@camilamacedo86  Thanks

**Comment by philbrookes** [comment]
It is normal to not be able to login on the CLI using a username / password when the auth is provided by SSO. This login needs to be performed by logging into the webui, copying the login token and using that in the CLI.

**Comment by tremes** [comment]
@philbrookes Don't agree. This used to work for me after https://github.com/integr8ly/installation/commit/7fcad7624e21d6d618bfaa3035f7a5d32a1d3c53

**Comment by philbrookes** [comment]
https://github.com/integr8ly/installation/pull/202

**Comment by camilamacedo86** [comment]
Closing it since the PR with the fix is already merged. @tremes please feel free to re-open if the issue still.
