### ISSUE TITLE
Apicurio project still installed after the uninstall playbook executions

### ISSUE THREAD

**Issue by trepel** [integr8ly/installation#217]
## Description
Apicurio project still installed after the uninstall playbook executions

## Expected Behavior
Uninstall playbook should remove Apicurio. I am not sure if there are other things to do apart form 'apicurio' namespace removal.

## Actual Behavior
Apicurio namespace is left intact by uninstall playbook
## Environment

* Operating system: RHDSY
* OpenShift version:
```shell
oc version
oc v3.10.14
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master1.london-7948.internal:443
openshift v3.10.14
kubernetes v1.10.0+b81c8f8
[root@bastion evals]# 
```
* Ansible version:

```shell
[root@bastion evals]# ansible --version
ansible 2.4.6.0
  config file = /root/installation/evals/ansible.cfg
  configured module search path = [u'/root/installation/evals/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[root@bastion evals]# 
```
* Project Version/Tag: master at 03/12/2018

## Steps to reproduce
1. Create an OCP instance by RHDSY. See [here](https://github.com/integr8ly/installation#using-red-hat-product-demo-system-to-have-an-openshift-instance-valid-just-for-partners-and-redhatters)
2. Run the installation with the launcher.  `ansible-playbook -i inventories/hosts playbooks/install.yml -e github_client_id=xxx -e github_client_secret=xxx`
3. Run the uninstall playbook(`ansible-playbook -i inventories/hosts playbooks/uninstall.yml`)
4. Check if the apicurio was removed by running the command "oc get projects"

```shell
PLAY RECAP ********************************************************************************************************************************************************
127.0.0.1                  : ok=37   changed=29   unreachable=0    failed=0   
master1.cmacedo-b37c.internal : ok=7    changed=6    unreachable=0    failed=0   

[root@bastion evals]# oc get projects
NAME                                DISPLAY NAME   STATUS
apicurio                                           Active
default                                            Active
kube-public                                        Active
kube-service-catalog                               Active
kube-system                                        Active
management-infra                                   Active
ocp-workshop                                       Active
openshift                                          Active
openshift-ansible-service-broker                   Active
openshift-infra                                    Active
openshift-logging                                  Active
openshift-node                                     Active
openshift-sdn                                      Active
openshift-template-service-broker                  Active
openshift-web-console                              Active
[root@bastion evals]# 
```

**Comment by camilamacedo86** [comment]
@trepel could you check this one? I was not able to reproduce this in the master branch. If for you still the problem, could you describe the steps that you are doing to check the "apicurio namespace"? As for example, could you describe the command used?

**Comment by camilamacedo86** [comment]
Hi @trepel,

I could reproduce the scenario and I will add the info in the first comment. Really tks

**Comment by trepel** [comment]
PR that fixes this has been merged: https://github.com/integr8ly/installation/pull/229/files
