### ISSUE TITLE
 [WARNING]: Consider using template or lineinfile module rather than running sed is faced when the uninstall playbook is executed

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/installation#231]
## Description
 [WARNING]: Consider using the template or lineinfile module rather than running sed is faced when the uninstall playbook is executed
## Expected Behavior

Do not get warnings regards deprecated methods and etc  .. 

## Actual Behavior
```shell
TASK [rhsso : Remove RH-SSO identity provider from master config] *************************************************************************************************
 [WARNING]: Consider using template or lineinfile module rather than running sed

```

## Steps to reproduce
1. Create an OCP instance by RHDSY. See [here](https://github.com/integr8ly/installation#using-red-hat-product-demo-system-to-have-an-openshift-instance-valid-just-for-partners-and-redhatters)
2. Run the installation with the launcher.  `ansible-playbook -i inventories/hosts playbooks/install.yml -e github_client_id=xxx -e github_client_secret=xxx`
3. Run the uninstall playbook(`ansible-playbook -i inventories/hosts playbooks/uninstall.yml`)

**Comment by odra** [comment]
We are kinda of replacing/removing a section in the master config file the `lineinfile`module  proved a bit unreliable when compared with sed.

What I think we could do is to set the `warn` property to `false` so ansible's warn message won't show up.
