### ISSUE TITLE
apicurio ns hangs on uninstall due to finalizer

### ISSUE THREAD

**Issue by maleck13** [integr8ly/installation#244]
## Description
When running the uninstall playbook apicurio ns hangs as the opertor is gone but the finaliser is still on the apicuriodeployment resources

## Expected Behavior
ns deleted

Workaround is to remove the finalizer yourself

solution is to remove the resource first and then remove the ns

ping @odra

**Comment by tremes** [comment]
@maleck13 Hey it's the same like https://issues.jboss.org/browse/INTLY-103 right?

**Comment by trepel** [comment]
Fixed by https://github.com/integr8ly/installation/pull/247
