### ISSUE TITLE
Erro "An error occurred getting the metrics" when go inside of the integr8ly projects

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/installation#253]
## Description
For all projects after the installation is shown an error regards get metrics which requires the certificate. 

## Expected Behavior
No see the error and do not be required to perform the workaround. 

## Actual Behavior
<img width="1411" alt="screenshot 2018-12-11 at 08 09 09" src="https://user-images.githubusercontent.com/7708031/49786687-8a89d300-fd1c-11e8-80ff-371127e541f1.png">

## Environment

* Operating system: RHEL / RHDPS
* OpenShift version: 
```shell
$ oc version
oc v3.10.14
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
* Ansible version:
```shell
$ ansible --version
[WARNING]: log file at /root/ansible.log is not writeable and we cannot create it, aborting

ansible 2.4.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
* Project Version/Tag: master https://github.com/integr8ly/installation/commit/87af58338d1801c40408b821bd562a1568284945

## Steps to reproduce

1. Create an instance in RHPDS. See [here](https://github.com/integr8ly/installation#using-red-hat-product-demo-system-to-have-an-openshift-instance-valid-just-for-partners-and-redhatters)
2. Following the steps to install and run the installer with the launcher variables ( `ansible-playbook -i inventories/hosts playbooks/install.yml -e github_client_id=X -e github_client_secret=X` ). See [here](https://github.com/integr8ly/installation#installing-from-rhpds)
3. Login in the OCP with the user `admin@example.com` and password is `Password1`
4. Go inside in any project and check the error message.

## Workaround
1. Click on in the link `Open metrics URL` (E.g https://hawkular-metrics.apps.final310-4393.openshiftworkshop.com/hawkular/metrics)
2. Accepted manually the certificate
3. See the following result, then when came back to the projects and refresh the console this error will no longer be faced. 

<img width="1206" alt="screenshot 2018-12-11 at 08 09 26" src="https://user-images.githubusercontent.com/7708031/49786994-61b60d80-fd1d-11e8-9dd3-f8582d7090c3.png">

**Comment by david-martin** [comment]
There is nothing we can do about this as it's an OpenShift feature.
In PDS however, there should be valid letsencrypt certs, which should mean it doesn't happen there at least
