### ISSUE TITLE
Error "/usr/share/nginx/html/launch/wizard" failed (2: No such file or directory)"

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/installation#254]
## Description
The error "/usr/share/nginx/html/launch/wizard" failed (2: No such file or directory)" is faced in the logs. Shows that the front end project is not finding a required/expected file. 

## Expected Behavior
Not see the error in the logs

## Actual Behavior
```shell
2018/12/11 01:32:22 [error] 18#0: *916 open() "/usr/share/nginx/html/launch/wizard" failed (2: No such file or directory), client: 10.1.4.1, server: _, request: "GET /launch/wizard HTTP/1.1", host: "10.1.4.12:8080"
```
<img width="1266" alt="screenshot 2018-12-11 at 08 39 46" src="https://user-images.githubusercontent.com/7708031/49788094-56181600-fd20-11e8-81ac-933085c59858.png">

## Environment

* Operating system: RHEL / RHDPS
* OpenShift version: 
```shell
$ oc version
oc v3.10.14
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
* Ansible version:
```shell
$ ansible --version
[WARNING]: log file at /root/ansible.log is not writeable and we cannot create it, aborting
ansible 2.4.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
* Project Version/Tag: master https://github.com/integr8ly/installation/commit/87af58338d1801c40408b821bd562a1568284945

## Steps to reproduce

1. Create an instance in RHPDS. See [here](https://github.com/integr8ly/installation#using-red-hat-product-demo-system-to-have-an-openshift-instance-valid-just-for-partners-and-redhatters)
2. Following the steps to install and run the installer with the launcher variables ( `ansible-playbook -i inventories/hosts playbooks/install.yml -e github_client_id=X -e github_client_secret=X` ). See [here](https://github.com/integr8ly/installation#installing-from-rhpds)
3. Login in the OCP with the user `admin@example.com` and password is `Password1`
4. Go inside in any project launcher and check the pod `launcher-frontend`

**Comment by camilamacedo86** [comment]
The path " /usr/share/nginx/html" is the default of nginx. See [here](https://serverfault.com/questions/920880/nginx-defaults-to-usr-share-nginx-html)

**Comment by david-martin** [comment]
This looks to be fixed in https://github.com/integr8ly/installation/pull/169
