### ISSUE TITLE
Unable to login with sso in the launcher project

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/installation#255]
## Description
Unable to log in with SSO in the launcher project. 

## Expected Behavior
Be able to login in the launcher using SSO. 
 
## Actual Behavior
<img width="1128" alt="screenshot 2018-12-11 at 08 47 49" src="https://user-images.githubusercontent.com/7708031/49788526-785e6380-fd21-11e8-8633-951bfcc21cb3.png">

**IMPORTANT:** The error "Unexpected error when authenticating with identity provider" is faced when the launcher endpoint is called directly.

<img width="1165" alt="screenshot 2018-12-11 at 08 49 19" src="https://user-images.githubusercontent.com/7708031/49788616-b065a680-fd21-11e8-9fca-e4448b516025.png">

## Environment

* Operating system: RHEL / RHDPS
* OpenShift version: 
```shell
$ oc version
oc v3.10.14
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
* Ansible version:
```shell
$ ansible --version
[WARNING]: log file at /root/ansible.log is not writeable and we cannot create it, aborting

ansible 2.4.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
* Project Version/Tag: master https://github.com/integr8ly/installation/commit/87af58338d1801c40408b821bd562a1568284945

## Steps to reproduce

1. Create an instance in RHPDS. See [here](https://github.com/integr8ly/installation#using-red-hat-product-demo-system-to-have-an-openshift-instance-valid-just-for-partners-and-redhatters)
2. Following the steps to install and run the installer with the launcher variables ( `ansible-playbook -i inventories/hosts playbooks/install.yml -e github_client_id=X -e github_client_secret=X` ). See [here](https://github.com/integr8ly/installation#installing-from-rhpds)
**IMPORTANT:** The GitHub OAuth app was updated as described in the steps of the README. See [here](https://github.com/integr8ly/installation#411-create-github-oauth-to-enable-github-authorization-for-launcher)
3. Login in the OCP with the user `admin@example.com` and password is `Password1`
4. Go inside in of the project launcher
5. Go to routers as follows.
<img width="1067" alt="screenshot 2018-12-11 at 08 47 11" src="https://user-images.githubusercontent.com/7708031/49788685-e73bbc80-fd21-11e8-89f5-b565e62caece.png">
6. Click on in the router for SSO
<img width="1260" alt="screenshot 2018-12-11 at 08 47 22" src="https://user-images.githubusercontent.com/7708031/49788717-fcb0e680-fd21-11e8-9b21-cf25df9f44d7.png">

7. Click on in administration console

8. Try to login with:

- evals@example.com / Password1
- admin@example.com / Password1
- GitHub user/login

**Comment by david-martin** [comment]
> Click on in the router for SSO

SSO Integration for Launcher is for users logging in to Launcher, not SSO.
i.e. you login to Launcher Wizard using your OpenShift credentials.

The credentials for logging into Launchers SSO instance are in env vars
