### ISSUE TITLE
Outh setup is not working

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/installation#257]
## Description
Outh setup is not working. 

## Expected Behavior
- Not be required to add login/user for the web app
- Count one user after it be used to authenticate

## Actual Behavior
It still likes 0 and is required to inform the login/user to login into the web app. 

<img width="1055" alt="screenshot 2018-12-11 at 09 38 13" src="https://user-images.githubusercontent.com/7708031/49791640-d6427980-fd28-11e8-8d53-ee6923ca04b2.png">

## Environment

* Operating system: RHEL / RHDPS
* OpenShift version: 
```shell
$ oc version
oc v3.10.14
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
* Ansible version:
```shell
$ ansible --version
[WARNING]: log file at /root/ansible.log is not writeable and we cannot create it, aborting

ansible 2.4.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
* Project Version/Tag: master https://github.com/integr8ly/installation/commit/87af58338d1801c40408b821bd562a1568284945

## Steps to reproduce

1. Create an instance in RHPDS. See [here](https://github.com/integr8ly/installation#using-red-hat-product-demo-system-to-have-an-openshift-instance-valid-just-for-partners-and-redhatters)
2. Following the steps to install and run the installer with the launcher variables ( `ansible-playbook -i inventories/hosts playbooks/install.yml -e github_client_id=X -e github_client_secret=X` ). See [here](https://github.com/integr8ly/installation#installing-from-rhpds)
**IMPORTANT:** The GitHub OAuth app was updated as described in the steps of the README. See [here](https://github.com/integr8ly/installation#411-create-github-oauth-to-enable-github-authorization-for-launcher)
3. Login in the OCP with the user `admin@example.com` and password is `Password1`
4. Go inside of webapp >> routers
5. Click on in the router, then is required to inform login/pwd

**Comment by david-martin** [comment]
> 4\. Go inside of webapp >> routers

Github auth is only used when you 'Authorize' Launcher (in the wizard) to your github account.
I'd only expect to see the users count updated then

**Comment by camilamacedo86** [comment]
Closing it since is open for too long and probably is outdated.
