### ISSUE TITLE
TASK [rhsso : Update latest RH-SSO image stream and templates] FAILED

### ISSUE THREAD

**Issue by nickschuetz** [integr8ly/installation#84]
When running the installer for all apps against an on-prem OCP 3.10 installation:

`ansible-playbook -i inventories/hosts playbooks/install.yml`

I get the following error and the installation fails:

> TASK [rhsso : Update latest RH-SSO image stream and templates] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
failed: [127.0.0.1] (item=sso72-image-stream.json) => {"changed": true, "cmd": "oc replace -n openshift --force -f https://raw.githubusercontent.com/jboss-openshift/application-templates/ose-v1.4.11/sso//sso72-image-stream.json", "delta": "0:05:00.714054", "end": "2018-10-09 15:42:38.819619", "item": "sso72-image-stream.json", "msg": "non-zero return code", "rc": 1, "start": "2018-10-09 15:37:38.105565", "stderr": "error: timed out waiting for the condition", "stderr_lines": ["error: timed out waiting for the condition"], "stdout": "imagestream.image.openshift.io \"redhat-sso72-openshift\" deleted", "stdout_lines": ["imagestream.image.openshift.io \"redhat-sso72-openshift\" deleted"]}
failed: [127.0.0.1] (item=sso72-x509-postgresql-persistent.json) => {"changed": true, "cmd": "oc replace -n openshift --force -f https://raw.githubusercontent.com/jboss-openshift/application-templates/ose-v1.4.11/sso//sso72-x509-postgresql-persistent.json", "delta": "0:05:00.731399", "end": "2018-10-09 15:47:39.884173", "item": "sso72-x509-postgresql-persistent.json", "msg": "non-zero return code", "rc": 1, "start": "2018-10-09 15:42:39.152774", "stderr": "error: timed out waiting for the condition", "stderr_lines": ["error: timed out waiting for the condition"], "stdout": "template.template.openshift.io \"sso72-x509-postgresql-persistent\" deleted", "stdout_lines": ["template.template.openshift.io \"sso72-x509-postgresql-persistent\" deleted"]}

Note that this was issued from a remote bastion host with the proper master host defined in the inventory file.

**Comment by maleck13** [comment]
ping @pmccarthy any thoughts on this issue?

**Comment by jasonmadigan** [comment]
@aidenkeating - can you ping @nickschuetz & work with him on this?

**Comment by nickschuetz** [comment]
I think this may have been OpenShift in a bad state within my volatile lab.
